

route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: junchenp1018@gmail.com
    from: junchenp1018@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "junchenp1018@gmail.com"
    auth_identity: "junchenp1018@gmail.com"
    auth_password: "xusmzdmbnzejsdlt"