version: '3.0'

services:

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules:/alertmanager/alert.rules
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  alertmanager:
    image: prom/alertmanager
    volumes:
         - ./alertmanager.yml:/alertmanager.yml
    command:
        - '--config.file=/alertmanager.yml'
    ports:
        - '9093:9093'

  grafana:
    image: grafana/grafana
    ports:
        - '3000:3000'